### ISSUE TITLE
Build Fails, Request Name Conflict

### ISSUE THREAD

**Issue by JeremyRubin** [stackbuilders/twitter-feed#1]
src/Web/Twitter/Feed.hs:116:52:
    Couldn't match expected type ‘http-client-0.3.6:Network.HTTP.Client.Types.Request’
                with actual type ‘Request m'0’
    NB: ‘http-client-0.3.6:Network.HTTP.Client.Types.Request’
          is defined in ‘Network.HTTP.Client.Types’
              in package ‘http-client-0.3.6’
        ‘Request’
          is defined in ‘Network.HTTP.Conduit.Types’
              in package ‘http-conduit-1.9.6’
    Relevant bindings include
      req :: Request m'0 (bound at src/Web/Twitter/Feed.hs:114:3)
    In the third argument of ‘signOAuth’, namely ‘req’
    In a stmt of a 'do' block:
      signedreq <- signOAuth oauth credential req

src/Web/Twitter/Feed.hs:117:20:
    Couldn't match expected type ‘Request
                                    (resourcet-0.4.10.2:Control.Monad.Trans.Resource.Internal.ResourceT
                                       IO)’
                with actual type ‘http-client-0.3.6:Network.HTTP.Client.Types.Request’
    NB: ‘Request’
          is defined in ‘Network.HTTP.Conduit.Types’
              in package ‘http-conduit-1.9.6’
        ‘http-client-0.3.6:Network.HTTP.Client.Types.Request’
          is defined in ‘Network.HTTP.Client.Types’
              in package ‘http-client-0.3.6’
    In the first argument of ‘httpLbs’, namely ‘signedreq’
    In a stmt of a 'do' block: httpLbs signedreq m
Failed to install twitter-feed-0.1.1.1

**Comment by jpvillaisaza** [comment]
We can close this for now, it doesn't seem like it's still an issue.
