### ISSUE TITLE
test-suite build failure

### ISSUE THREAD

**Issue by bergmark** [stackbuilders/twitter-feed#12]
```
reprocessing test suite 'twitter-library' for twitter-feed-0.1.1.5...

test/Suite.hs:5:18:
    Could not find module ‘Web.Twitter.Feed.Tests’
    Perhaps you meant
      Web.Twitter.Feed (needs flag -package-key twitter-feed-0.1.1.5@twitt_7m90iZvk4b67IYn9Rd5ofN)
      Web.Twitter.Feed (from twitter-feed-0.1.1.5@twitt_8ipPjJpqFvQ1jtGdajqFGt)
    Use -v to see a list of the files searched for.
```

ping @jpvillaisaza

**Comment by jpvillaisaza** [comment]
@bergmark Thanks for opening this issue. I'll close it as soon as we upload version 0.2.0.0 to Hackage.

**Comment by jpvillaisaza** [comment]
Fixed after 0872396 and version 0.2.0.0.

@bergmark Should we do anything else about https://github.com/fpco/stackage/commit/e37958c830b60592fe26dfa32e44ef0ca9ff721d? Thank you.

**Comment by bergmark** [comment]
I re-enabled both test suites, Usually sending a PR to stackage is the way to go.

**Comment by jpvillaisaza** [comment]
@bergmark Great, thank you very much.
