### ISSUE TITLE
Check dependency on HUnit 1.3

### ISSUE THREAD

**Issue by jpvillaisaza** [stackbuilders/twitter-feed#20]
Can we upgrade HUnit to < 1.4?

See https://github.com/fpco/stackage/issues/768.

**Comment by jpvillaisaza** [comment]
See https://github.com/haskell/test-framework/issues/15.

**Comment by jpvillaisaza** [comment]
And https://github.com/haskell/test-framework/pull/16.

**Comment by glguy** [comment]
test-framework-hunit supports HUnit 1.3 now

**Comment by jpvillaisaza** [comment]
@glguy Thanks, I'll try the new version now.

**Comment by jpvillaisaza** [comment]
Done. See https://github.com/stackbuilders/twitter-feed/commit/cf8cde8f6008977bed752840eb89c2dc76e585ab.
