### ISSUE TITLE
Use `stack` instead of `cabal` on Travis

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/twitter-feed#28]
@jsl since we are using `stack` for development and local testing, we should be consistent and to the same on Travis. Any thoughts @jsantos17, @jpvillaisaza, @CristhianMotoche @ExternalReality ?

**Comment by CristhianMotoche** [comment]
Yeah. I agree with you.

**Comment by jpvillaisaza** [comment]
@sestrella I agree with using Stack for Travis, but not for being consistent -- we have  a configuration for working with Stack, but the project should build successfully with either option (regardless of the one chosen for development).

**Comment by jsl** [comment]
Closing, since it looks like this was done in #30.
